services:
    web:
        build:
            context: .
            args:
                - DEV=true
        ports:
            - "8000:8000"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        depends_on:
            - db
        volumes:
            - ./app:/app
        command: python manage.py runserver 0.0.0.0:8000
    db:
        image: postgres:17-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
